// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:keklist/domain/repositories/debug_menu/object/debug_menu_object.dart';
import 'package:keklist/domain/repositories/mind/object/mind_object.dart';
import 'package:keklist/domain/repositories/settings/object/settings_object.dart';
import 'package:keklist/domain/repositories/weather/object/weather_cache_object.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DebugMenuObjectAdapter());
    registerAdapter(MindObjectAdapter());
    registerAdapter(SettingsObjectAdapter());
    registerAdapter(WeatherCacheObjectAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DebugMenuObjectAdapter());
    registerAdapter(MindObjectAdapter());
    registerAdapter(SettingsObjectAdapter());
    registerAdapter(WeatherCacheObjectAdapter());
  }
}
