name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Flutter analyze & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios_app:
    name: Build iOS
    runs-on: macos-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios

  build_android_app:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Decoding android/keystore.jks
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-zenmode.jks
    
      - name: Decoding android/key.properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}" | base64 --decode > android/key.properties

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle